const testData = {
  'menu': [{
    'icon': '',
    'items': [
      {
        'icon': 'scrm-cluemanage',
        'title': '线索管理',
        'content': '一句话介绍描述',
        'path': '/crownpin/cluemanage'
      }, {
        'icon': 'scrm-carPrice',
        'title': '购车询价',
        'content': '一句话介绍描述',
        'path': '/crownpin/purchase'
      }, {
        'icon': 'scrm-tryCarTime',
        'title': '试驾预约',
        'content': '线索一句话介绍描述',
        'path': '/crownpin/drive'
      }, {
        'icon': 'scrm-creatCard',
        'title': '建卡管理',
        'content': '线索一句话介绍描述',
        'path': '/crownpin/potential'
      }, {
        'icon': 'scrm-invite',
        'title': '邀约登记管理',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-potential',
        'title': '潜客管理',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-passengerflow',
        'title': '客流管理',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-defeated',
        'title': '战败列表',
        'content': '一句话介绍一句话介绍一句话介绍',
        'path': ''
      }, {
        'icon': 'scrm-complaint',
        'title': '申述列表',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-orderMan',
        'title': '订单管理',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-carExchange',
        'title': '二手车置换',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-smartCall',
        'title': '智能通话',
        'content': '线索一句话介绍描述',
        'path': ''
      }
    ],
    'title': "常用管理"
  }, {
    'icon': '',
    'items': [
      {
        'icon': 'scrm-setting',
        'title': '可选功能',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-customNotice',
        'title': '客户跟进提醒',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-customFrom',
        'title': '客户来源类型',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-potentialCustom',
        'title': '潜客自定义字段',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-talkSkill',
        'title': '常用话术设置',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-carProtocol',
        'title': '试驾协议书',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-tryCarSet',
        'title': '试驾车辆设置',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-defeatedReason',
        'title': '战败原因',
        'content': '线索一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-customReturn',
        'title': '成交客户回访设置',
        'content': '一句话介绍描述',
        'path': ''
      }, {
        'icon': 'scrm-tagSet',
        'title': '标签设置',
        'content': '一句话介绍描述',
        'path': ''
      }
    ],
    'title': "参数设置"
  }, {
    'icon': '',
    'items': [
      {
        'icon': 'scrm-baobiao',
        'title': '报表',
        'content': '一句话介绍描述',
        'path': ''
      }
    ],
    'title': "报表"
  }],
  'name': {
    '报表': 'baobiao',
    "常用话术设置": '',
    '成交客户回访': '',
    '订单管理': '',
    '二手车置换': '',
    '购车询价': '',
    '建卡管理': '',
    '可选功能设置': '',
    '客户来源类型': '',
    '客流根据提醒': '',
    '客流管理': 'passengerflow',
    '潜客管理': 'potential',
    '潜客自定义字段': 'potential-custom',
    '申述列表': 'complaint',
    '试驾车辆设置': 'try-car',
    '试驾协议书': 'car-protocol',
    '试驾预约': '',
    '线索管理': 'cluemanage',
    '邀约登记管理': 'invite',
    '战败列表': 'defeated',
    '战败原因': 'defeated-resaon',
    '智能通话': 'smart-'
  }
}

export default testData;